name: OAshies
version: '${project.version}'
main: io.github.onebytegh.oashies.OAshies
api-version: 1.19
authors: [ OneByte, ashswag ]
description: A plugin I made that would give you the powers mentioned in this video https://youtu.be/AVVQAU3lWZo
website: github.com/OneByteGH
depend: [ProtocolLib]
